### ISSUE TITLE
imagenet class labels

### ISSUE THREAD

**Issue by fredhohman** [poloclub/bluff#2]
are we sure [this data](https://github.com/poloclub/massif/blob/master/data/imagenet_tfrecords_labels.txt) is the right mapping for imagenet? 

the class ordering looks different than what I remember but I could just have a bad memory. can we confirm what summit used? should be [in here](https://github.com/fredhohman/summit-data/blob/master/data/imagenet.json).

**Comment by haekyu** [comment]
The order of labels in the data (tfrecord) and the model (modelzoo InceptionV1) are different. [Here](https://github.com/poloclub/bluff/blob/master/data/imagenet-labels.txt) you can find the both ordered labels.
